name: Draw ZMK keymaps

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/keymap_drawer.yml"
      - "keymap_drawer.config.yaml"
      - "config/**"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      commit_message: "[Draw] ${{ github.event.head_commit.message || 'manual run' }}"
      amend_commit: false
      install_branch: "main"
      keymap_patterns: "config/*.keymap"
      json_path: "config"
      config_path: "keymap_drawer.config.yaml"
      output_folder: "keymap-drawer"
      destination: "both"
      parse_args: ""
      draw_args: ""
